windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAFgAABVUAAALoAAAAAgAAABYAAAVTAAAC5gAAAAAAAAAABVYAAAACAAAA
    FgAABVMAAALm
  tabs:
  - history:
    - pinned: false
      title: start.duckduckgo.com
      url: https://start.duckduckgo.com/
    - pinned: false
      title: esp8266mod at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod&ia=web
    - pinned: false
      title: esp8266mod at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod&iax=images&ia=images
    - pinned: false
      title: esp8266mod at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod&ia=web
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: esp8266mod wiring at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod+wiring&ia=web
      zoom: 1.0
  - active: true
    history:
    - pinned: false
      title: esp8266mod flashses and shuts down at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod+flashses+and+shuts+down&ia=web
    - pinned: false
      title: esp8266mod shuts off at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod+shuts+off&ia=web
    - pinned: false
      title: esp8266mod powering at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266mod+powering&ia=web
    - active: true
      original-url: https://duckduckgo.com/?q=esp8266mod+powering&ia=web
      pinned: false
      scroll-pos:
        x: 0
        y: 902
      title: ESP8266MOD WiFi Module
      url: http://www.tinyosshop.com/index.php?route=product/product&product_id=908
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 5880
      title: ESP8266 - NURDspace
      url: https://nurdspace.nl/ESP8266
      zoom: 1.0
  - history:
    - pinned: false
      title: esp8266-12 at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266-12&ia=web
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: esp8266 pinout at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266+pinout&ia=web
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 4804
      title: 'Getting Started With the ESP8266 ESP-12: 8 Steps'
      url: https://www.instructables.com/id/Getting-Started-with-the-ESP8266-ESP-12/
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 6804
      title: esp8266-module-family [ESP8266 Support WIKI]
      url: https://www.esp8266.com/wiki/doku.php?id=esp8266-module-family&s[]=pinout
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: esp8266 gpio2 at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266+gpio2&ia=web
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 10089
      title: 'ESP8266 Pinout Reference: Which GPIO pins should you use? | Random Nerd
        Tutorials'
      url: https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: esp8266-01 schematic at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266-01+schematic&ia=web
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 1340
      title: ESP-01 Pin Outs and Schematic | Henry's Bench
      url: http://henrysbench.capnfatz.com/henrys-bench/arduino-projects-tips-and-more/esp8266-esp-01-pin-outs-and-schematics/
      zoom: 1.0
  - history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: ESP8266EX Pinouts and Connections | Henry's Bench
      url: http://henrysbench.capnfatz.com/henrys-bench/arduino-projects-tips-and-more/esp8266ex-pinouts-and-connections/
      zoom: 1.0
  - history:
    - pinned: false
      title: esp8266-12 schematic at DuckDuckGo
      url: https://duckduckgo.com/?q=esp8266-12+schematic&ia=web
    - active: true
      original-url: https://duckduckgo.com/?q=esp8266-12+schematic&ia=web
      pinned: false
      scroll-pos:
        x: 0
        y: 5242
      title: ESP8266 12e Pinout Schematic Circuit Diagram- NodeMCU
      url: https://circuit-diagramz.com/esp8266-12e-pinout-schematic-circuit-diagram/
      zoom: 1.0
